### ISSUE TITLE
util.deserialize() should return an IPLD-friendly object, not BitcoinjsBlock

### ISSUE THREAD

**Issue by Mr0grog** [ipld/js-ipld-bitcoin#26]
See also ipld/js-ipld#141.

`util.deserialize()`, which is what provides results to `ipld.get(cid)`, should return an object where the keys represent the same set of paths that can be resolved with `ipld.get(cid, path)`. Instead, it’s [currently returning](https://github.com/ipld/js-ipld-bitcoin/blob/b75bb649a930d2149bb722b46a6eb6bf0fbdd4f8/src/util.js#L58-L59) a `BitcoinjsBlock` instance, which is *very* different.

The exact format of the object depends on how we resolve the open question at the end of the original post in ipld/js-ipld#141.

**Comment by vmx** [comment]
I disagree. If you want a IPLD-friendly object use `resolve.resolve(binaryBlob, '/')`.

**Comment by Mr0grog** [comment]
Closing this issue — this was a misunderstanding between @vmx and I about the intended behavior. Instead, the real issue is a combination of ipld/interface-ipld-format#34 (which needs to be fixed in this resolver) and ipld/js-ipld#142 (which needs to be fixed in js-ipld).
