### ISSUE TITLE
Need new npm release for 'async' dependency fix

### ISSUE THREAD

**Issue by jhiesey** [ipld/js-ipld-bitcoin#29]
This commit: https://github.com/ipld/js-ipld-bitcoin/commit/c070fdf9729afecf66e6f864a598804020e8fca5 isn't published to npm so the missing dependency is still causing problems.

**Comment by vmx** [comment]
[Version 0.1.8 was released](https://github.com/ipld/js-ipld-bitcoin/releases/tag/v0.1.8).
